version: 2
updates:
  - package-ecosystem: "pip"
    directory: "./tasks"  # path of requirements.txt
    schedule:
      interval: "daily" # can be changed to weekly or monthly
    open-pull-requests-limit: 5  # to limit the number of open PRs from Dependabot
    commit-message:
      prefix: "fix"  # for commit messages created by Dependabot
