#!/bin/bash

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "Running yamllint..."
yamllint .

echo "Running ansible-lint..."
ansible-lint .

echo "Running OpenWISP QA checks..."
openwisp-qa-check --skip-isort \
                  --skip-flake8 \
                  --skip-black \
                  --skip-checkmigrations
