---
- name: Include variables for Debian 13
  ansible.builtin.include_vars:
    dir: "{{ role_path }}/vars"
    files_matching: "^debian-13.yml$"
  when:
    - ansible_distribution|string == 'Debian'
    - ansible_distribution_release|string == 'trixie'
  tags: [always]

- name: Include variables for Ubuntu 26.04
  ansible.builtin.include_vars:
    dir: "{{ role_path }}/vars"
    files_matching: "^ubuntu-26.yml$"
  when:
    - ansible_distribution|string == 'Ubuntu'
    - ansible_distribution_release|string == 'resolute'
  tags: [always]

- name: Import APT tasks
  ansible.builtin.import_tasks: apt.yml
  tags: [openwisp2, apt]

- name: Import SSH tasks
  ansible.builtin.import_tasks: ssh.yml
  tags: [openwisp2, ssh]

- name: Import system tasks
  ansible.builtin.import_tasks: system.yml
  tags: [openwisp2, system]

- name: Import pip tasks
  ansible.builtin.import_tasks: pip.yml
  tags: [openwisp2, pip]

# comprises django_secret_key.yml
- name: Import Django tasks
  ansible.builtin.import_tasks: django.yml
  tags: [openwisp2, django]

- name: Import FreeRADIUS tasks
  ansible.builtin.import_tasks: freeradius.yml
  when: openwisp2_radius and openwisp2_freeradius_install
  tags: [openwisp2, freeradius]

- name: Import supervisor tasks
  ansible.builtin.import_tasks: supervisor.yml
  tags: [openwisp2, supervisor]

- name: Import nginx tasks
  ansible.builtin.import_tasks: nginx.yml
  when: openwisp2_nginx_install
  tags: [openwisp2, nginx]

- name: Import cron tasks
  ansible.builtin.import_tasks: cron.yml
  tags: [openwisp2, cron]

- name: Import complete tasks
  ansible.builtin.import_tasks: complete.yml
  tags: [openwisp2]
