---

- name: Converge
  hosts: all
  become: true

  vars:
    openwisp2_network_topology: true
    openwisp2_firmware_upgrader: true
    openwisp2_radius: true
    openwisp2_controller_subnet_division: true
    openwisp2_uwsgi_extra_conf: |
      single-interpreter=True

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Remove the .dockerenv file
      file:
        path: /.dockerenv
        state: absent

  roles:
    - role: openwisp.openwisp2
