---

- name: Converge
  hosts: all
  become: true

  vars:
    openwisp2_network_topology: true
    openwisp2_firmware_upgrader: true
    openwisp2_radius: true
    openwisp2_controller_subnet_division: true
    openwisp2_uwsgi_extra_conf: |
      single-interpreter=True

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Remove the .dockerenv file
      file:
        path: /.dockerenv
        state: absent
  # TODO: Remove before merging
  tasks:
    - name: Install openwisp-utils metric collection
      pip:
        name: "openwisp-utils @ https://github.com/openwisp/openwisp-utils/tarball/issues/360-clean-insights"
        state: forcereinstall
        virtualenv: "{{ virtualenv_path }}"
        virtualenv_python: "{{ openwisp2_python }}"
      environment:
        SETUPTOOLS_USE_DISTUTILS: stdlib
      notify: Reload application
      tags: [extra_pip, molecule-idempotence-notest]

  roles:
    - role: openwisp.openwisp2
