---

dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint . || true
  ansible-lint || true
platforms:
  - name: "${ROLE_NAME:-instance}-${MOLECULE_DISTRO}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO}-ansible:${tag:-latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    MOLECULE_NO_LOG: false
  playbooks:
    converge: ../resources/${MOLECULE_PLAYBOOK:-converge.yml}
    verify: ../resources/verify.yml
  config_options:
    defaults:
      stdout_callback: yaml
      bin_ansible_callbacks: true
  inventory:
    host_vars:
      openwisp2-debian11:
        openwisp2_django_version: "django~=4.2.0"

verifier:
  name: ansible
